_: {
  projectRootFile = "flake.nix";

  programs = {
    nixfmt.enable = true;
    deadnix.enable = true;

    ruff-check.enable = true;
    ruff-format.enable = true;

    clang-format.enable = true;

    shfmt.enable = true;
    shellcheck.enable = true;
  };

  settings = {
    formatter.shellcheck.options = [
      "--external-sources"
      "--severity=warning"
    ];

    global.excludes = [
      "*.pdf"
      "*.pyc"
      "firmware/build/**"
      # Vendored verbatim from the Pico SDK; reformatting it would fork upstream.
      "firmware/pico_sdk_import.cmake"
      # Regenerated by cli/tools/gen_font.py, which owns its layout.
      "cli/epaper/font.py"
    ];
  };
}
