"""Generate the embedded ASCII table from Spleen's PSF1 file."""
import pathlib
import sys

blob = pathlib.Path(sys.argv[1]).read_bytes()
if blob[:2] != b'\x36\x04' or blob[3] != 16 or len(blob) < 4 + 127 * 16:
    raise SystemExit('expected an 8x16 PSF1 font')
header = '''# Generated by cli/tools/gen_font.py from spleen-8x16.psfu.
# Spleen Copyright (c) 2018-2024 Frederic Cambus. BSD-2-Clause.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

GLYPHS = bytes.fromhex(
'''
rows = ['    "' + blob[4+c*16:4+(c+1)*16].hex() + '"' for c in range(32, 127)]
pathlib.Path(sys.argv[2]).write_text(header + '\n'.join(rows) + '\n)\n\ndef glyph(character):\n    code = ord(character) if len(character) == 1 else 63\n    if not 32 <= code <= 126:\n        code = 63\n    return GLYPHS[(code - 32) * 16:(code - 31) * 16]\n')
