//! Byte-for-byte parity with the Python CLI's protocol module.
//!
//! The vectors are generated by tests/vectors.json, produced from
//! cli/epaper/protocol.py; regenerate them if the wire format ever changes.

use std::collections::HashMap;

use epaper::protocol::*;

fn vectors() -> serde_json::Value {
    let raw = include_str!("vectors.json");
    serde_json::from_str(raw).expect("vectors.json is valid JSON")
}

fn decode_hex(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&text[index..index + 2], 16).expect("valid hex"))
        .collect()
}

fn cases() -> HashMap<String, Vec<u8>> {
    vectors()["cases"]
        .as_array()
        .expect("cases is an array")
        .iter()
        .map(|case| {
            (
                case["name"].as_str().expect("name").to_string(),
                decode_hex(case["hex"].as_str().expect("hex")),
            )
        })
        .collect()
}

#[test]
fn encoded_frames_match_python() {
    let cases = cases();
    let checks: Vec<(&str, Vec<u8>)> = vec![
        ("encode_ping", encode(Command::Ping as u8, 0, &[]).unwrap()),
        (
            "encode_blit_seq255",
            encode(
                Command::Blit as u8,
                255,
                &(0..=255u8).cycle().take(256 * 4).collect::<Vec<u8>>(),
            )
            .unwrap(),
        ),
        (
            "encode_status_seq7",
            encode(Command::Status as u8, 7, &[]).unwrap(),
        ),
        (
            "encode_maxpayload",
            encode(Command::ImgData as u8, 3, &[0xA5; 4096]).unwrap(),
        ),
    ];
    for (name, actual) in checks {
        assert_eq!(&actual, &cases[name], "frame {name} diverges from Python");
    }
}

#[test]
fn command_constructors_match_python() {
    let cases = cases();
    let mut checks: Vec<(&str, (Command, Vec<u8>))> = vec![
        ("ctor_ping", ping()),
        ("ctor_info", info()),
        ("ctor_status", status()),
        ("ctor_sleep", sleep()),
        ("ctor_bootsel", reset_bootsel()),
        ("ctor_clear_white", clear(false)),
        ("ctor_clear_black", clear(true)),
        ("ctor_refresh_full", refresh(true)),
        ("ctor_refresh_partial", refresh(false)),
        ("ctor_img_begin", img_begin()),
        ("ctor_img_end_full", img_end(false)),
        ("ctor_img_end_partial", img_end(true)),
    ];
    checks.push(("ctor_img_data", img_data(4090, &[b'z'; 100]).unwrap()));
    checks.push((
        "ctor_blit",
        blit(3, 32, 4, 8, &(0..32u8).collect::<Vec<u8>>()).unwrap(),
    ));

    for (name, (command, payload)) in checks {
        let mut actual = vec![command as u8];
        actual.extend_from_slice(&payload);
        assert_eq!(
            &actual, &cases[name],
            "constructor {name} diverges from Python"
        );
    }
}

#[test]
fn crc_matches_python() {
    let expected = &vectors()["crcs"];
    assert_eq!(
        crc16(b"123456789") as u64,
        expected["123456789"].as_u64().unwrap()
    );
    assert_eq!(crc16(b"") as u64, expected["empty"].as_u64().unwrap());
    assert_eq!(
        crc16(&[0xEB, 0x90]) as u64,
        expected["eb90"].as_u64().unwrap()
    );
    let long: Vec<u8> = (0..=255u8).cycle().take(256 * 8).collect();
    assert_eq!(crc16(&long) as u64, expected["long"].as_u64().unwrap());
}

#[test]
fn status_parsing_matches_python() {
    let root = vectors();
    let payload = decode_hex(root["status_hex"].as_str().unwrap());
    let expected: Vec<u64> = root["status_fields"]
        .as_array()
        .unwrap()
        .iter()
        .map(|value| value.as_u64().unwrap())
        .collect();
    let status = parse_status(&payload).unwrap();
    let actual = vec![
        status.busy as u64,
        status.partials_since_full as u64,
        status.ms_since_full as u64,
        status.bbox_valid as u64,
        status.x_byte0 as u64,
        status.y0 as u64,
        status.x_byte1 as u64,
        status.y1 as u64,
    ];
    assert_eq!(actual, expected);
}

/// The Python decoder is fed the same adversarial stream in
/// cli/tests/test_protocol.py; both must recover exactly one frame.
#[test]
fn decoder_resyncs_like_python() {
    let cases = cases();
    let valid = &cases["encode_status_seq7"];
    let mut damaged = valid.clone();
    *damaged.last_mut().unwrap() ^= 1;

    let mut stream = b"junk\xeb".to_vec();
    stream.extend_from_slice(&damaged);
    stream.extend_from_slice(valid);

    let frames = Decoder::new().feed(&stream);
    assert_eq!(frames.len(), 1);
    assert_eq!(frames[0].seq, 7);
    assert_eq!(frames[0].frame_type, Command::Status as u8);
}
