//! Byte-for-byte parity with the Python CLI's protocol module.
//!
//! The vectors are generated by tests/vectors.json, produced from
//! cli/epaper/protocol.py; regenerate them if the wire format ever changes.

use std::collections::HashMap;

use epaper::protocol::*;

fn vectors() -> serde_json::Value {
    let raw = include_str!("vectors.json");
    serde_json::from_str(raw).expect("vectors.json is valid JSON")
}

fn decode_hex(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&text[index..index + 2], 16).expect("valid hex"))
        .collect()
}

fn cases() -> HashMap<String, Vec<u8>> {
    vectors()["cases"]
        .as_array()
        .expect("cases is an array")
        .iter()
        .map(|case| {
            (
                case["name"].as_str().expect("name").to_string(),
                decode_hex(case["hex"].as_str().expect("hex")),
            )
        })
        .collect()
}

#[test]
fn encoded_frames_match_python() {
    let cases = cases();
    let checks: Vec<(&str, Vec<u8>)> = vec![
        ("encode_ping", encode(Command::Ping as u8, 0, &[]).unwrap()),
        (
            "encode_blit_seq255",
            encode(
                Command::Blit as u8,
                255,
                &(0..=255u8).cycle().take(256 * 4).collect::<Vec<u8>>(),
            )
            .unwrap(),
        ),
        (
            "encode_status_seq7",
            encode(Command::Status as u8, 7, &[]).unwrap(),
        ),
        (
            "encode_maxpayload",
            encode(Command::ImgData as u8, 3, &[0xA5; 4096]).unwrap(),
        ),
    ];
    for (name, actual) in checks {
        assert_eq!(&actual, &cases[name], "frame {name} diverges from Python");
    }
}

#[test]
fn command_constructors_match_python() {
    let cases = cases();
    let mut checks: Vec<(&str, (Command, Vec<u8>))> = vec![
        ("ctor_ping", ping()),
        ("ctor_info", info()),
        ("ctor_status", status()),
        ("ctor_sleep", sleep()),
        ("ctor_bootsel", reset_bootsel()),
        ("ctor_clear_white", clear(false)),
        ("ctor_clear_black", clear(true)),
        ("ctor_refresh_full", refresh(true)),
        ("ctor_refresh_partial", refresh(false)),
        ("ctor_img_begin", img_begin()),
        ("ctor_img_end_full", img_end(false)),
        ("ctor_img_end_partial", img_end(true)),
    ];
    checks.push(("ctor_img_data", img_data(4090, &[b'z'; 100]).unwrap()));
    checks.push((
        "ctor_blit",
        blit(3, 32, 4, 8, &(0..32u8).collect::<Vec<u8>>()).unwrap(),
    ));

    for (name, (command, payload)) in checks {
        let mut actual = vec![command as u8];
        actual.extend_from_slice(&payload);
        assert_eq!(
            &actual, &cases[name],
            "constructor {name} diverges from Python"
        );
    }
}

/// Rejection parity: a constructor that Python refuses must not be accepted
/// here, and vice versa. Byte-level vectors only cover the accepted cases.
#[test]
fn constructor_boundaries_match_python() {
    let root = vectors();
    let expected: HashMap<String, bool> = root["boundaries"]
        .as_array()
        .expect("boundaries is an array")
        .iter()
        .map(|case| {
            (
                case["name"].as_str().expect("name").to_string(),
                case["accepted"].as_bool().expect("accepted"),
            )
        })
        .collect();

    let accepted: Vec<(&str, bool)> = vec![
        ("encode_payload_4096", encode(1, 0, &[b'x'; 4096]).is_ok()),
        ("encode_payload_4097", encode(1, 0, &[b'x'; 4097]).is_ok()),
        ("img_data_4090", img_data(0, &[b'x'; 4090]).is_ok()),
        ("img_data_4091", img_data(0, &[b'x'; 4091]).is_ok()),
        ("img_data_end_exact", img_data(47990, &[b'x'; 10]).is_ok()),
        ("img_data_end_over", img_data(47990, &[b'x'; 11]).is_ok()),
        ("img_data_offset_48000", img_data(48000, &[]).is_ok()),
        (
            "blit_full_width",
            blit(0, 0, 100, 40, &[b'z'; 4000]).is_ok(),
        ),
        ("blit_x_at_edge", blit(99, 0, 1, 1, b"z").is_ok()),
        ("blit_x_past_edge", blit(100, 0, 1, 1, b"z").is_ok()),
        ("blit_width_overruns", blit(99, 0, 2, 1, b"zz").is_ok()),
        ("blit_y_at_edge", blit(0, 479, 1, 1, b"z").is_ok()),
        ("blit_y_past_edge", blit(0, 480, 1, 1, b"z").is_ok()),
        ("blit_height_overruns", blit(0, 479, 1, 2, b"zz").is_ok()),
        ("blit_zero_width", blit(0, 0, 0, 1, b"").is_ok()),
        ("blit_zero_height", blit(0, 0, 1, 0, b"").is_ok()),
        ("blit_body_too_short", blit(0, 0, 2, 2, b"zzz").is_ok()),
        ("blit_body_too_long", blit(0, 0, 2, 2, b"zzzzz").is_ok()),
        (
            "blit_body_at_limit",
            blit(0, 0, 1, 4088, &[b'z'; 4088]).is_ok(),
        ),
        (
            "blit_body_past_limit",
            blit(0, 0, 1, 4089, &[b'z'; 4089]).is_ok(),
        ),
        ("status_15_bytes", parse_status(&[b'x'; 15]).is_ok()),
        ("status_16_bytes", parse_status(&[b'x'; 16]).is_ok()),
        ("status_17_bytes", parse_status(&[b'x'; 17]).is_ok()),
    ];

    assert_eq!(
        accepted.len(),
        expected.len(),
        "every generated boundary must be checked"
    );
    for (name, got) in accepted {
        assert_eq!(
            got, expected[name],
            "{name}: Rust accepted={got}, Python accepted={}",
            expected[name]
        );
    }
}

#[test]
fn crc_matches_python() {
    let expected = &vectors()["crcs"];
    assert_eq!(
        crc16(b"123456789") as u64,
        expected["123456789"].as_u64().unwrap()
    );
    assert_eq!(crc16(b"") as u64, expected["empty"].as_u64().unwrap());
    assert_eq!(
        crc16(&[0xEB, 0x90]) as u64,
        expected["eb90"].as_u64().unwrap()
    );
    let long: Vec<u8> = (0..=255u8).cycle().take(256 * 8).collect();
    assert_eq!(crc16(&long) as u64, expected["long"].as_u64().unwrap());
}

#[test]
fn status_parsing_matches_python() {
    let root = vectors();
    let payload = decode_hex(root["status_hex"].as_str().unwrap());
    let expected: Vec<u64> = root["status_fields"]
        .as_array()
        .unwrap()
        .iter()
        .map(|value| value.as_u64().unwrap())
        .collect();
    let status = parse_status(&payload).unwrap();
    let actual = vec![
        status.busy as u64,
        status.partials_since_full as u64,
        status.ms_since_full as u64,
        status.bbox_valid as u64,
        status.x_byte0 as u64,
        status.y0 as u64,
        status.x_byte1 as u64,
        status.y1 as u64,
    ];
    assert_eq!(actual, expected);
}

/// The Python decoder is fed the same adversarial stream in
/// cli/tests/test_protocol.py; both must recover exactly one frame.
#[test]
fn decoder_resyncs_like_python() {
    let cases = cases();
    let valid = &cases["encode_status_seq7"];
    let mut damaged = valid.clone();
    *damaged.last_mut().unwrap() ^= 1;

    let mut stream = b"junk\xeb".to_vec();
    stream.extend_from_slice(&damaged);
    stream.extend_from_slice(valid);

    let frames = Decoder::new().feed(&stream);
    assert_eq!(frames.len(), 1);
    assert_eq!(frames[0].seq, 7);
    assert_eq!(frames[0].frame_type, Command::Status as u8);
}
