#!/usr/bin/env python3
"""Generate src/font8x16.h from a PSF1 console font (spleen-8x16.psfu).

Emits glyphs for printable ASCII 0x20..0x7E only; the console engine maps
everything else to a blank cell.
"""
import sys

PSF1_MAGIC = b"\x36\x04"
FIRST, LAST = 0x20, 0x7E


def main(psf_path: str, out_path: str) -> None:
    blob = open(psf_path, "rb").read()
    if blob[:2] != PSF1_MAGIC:
        raise SystemExit(f"not a PSF1 font: {psf_path}")
    charsize = blob[3]
    if charsize != 16:
        raise SystemExit(f"expected 16 rows per glyph, got {charsize}")
    glyphs = blob[4:]

    rows = []
    for cp in range(FIRST, LAST + 1):
        g = glyphs[cp * charsize:(cp + 1) * charsize]
        if len(g) != charsize:
            raise SystemExit(f"font too short for codepoint {cp:#x}")
        body = ", ".join(f"0x{b:02X}" for b in g)
        rows.append(f"    {{ {body} }}, /* {chr(cp)!r} */")

    with open(out_path, "w") as f:
        f.write(
            "/* Generated by tools/gen_font.py from spleen-8x16.psfu. Do not edit.\n"
            " *\n"
            " * Spleen is Copyright (c) 2018-2024, Frederic Cambus, BSD-2-Clause.\n"
            " * Each glyph is 16 rows of 8 pixels; bit 7 is the leftmost pixel and a\n"
            " * set bit is ink.\n"
            " */\n"
            "#ifndef FONT8X16_H\n"
            "#define FONT8X16_H\n\n"
            "#include <stdint.h>\n\n"
            "#define FONT_FIRST_CHAR 0x20\n"
            "#define FONT_LAST_CHAR  0x7E\n"
            "#define FONT_WIDTH      8\n"
            "#define FONT_HEIGHT     16\n\n"
            "static const uint8_t font8x16[FONT_LAST_CHAR - FONT_FIRST_CHAR + 1]"
            "[FONT_HEIGHT] = {\n"
        )
        f.write("\n".join(rows))
        f.write("\n};\n\n#endif\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
